/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SentryDemoRouteImport } from './routes/sentry-demo'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInIndexRouteImport } from './routes/sign-in/index'
import { Route as ApiInngestRouteImport } from './routes/api/inngest'

const SentryDemoRoute = SentryDemoRouteImport.update({
  id: '/sentry-demo',
  path: '/sentry-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInIndexRoute = SignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInngestRoute = ApiInngestRouteImport.update({
  id: '/api/inngest',
  path: '/api/inngest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sentry-demo': typeof SentryDemoRoute
  '/api/inngest': typeof ApiInngestRoute
  '/sign-in/': typeof SignInIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sentry-demo': typeof SentryDemoRoute
  '/api/inngest': typeof ApiInngestRoute
  '/sign-in': typeof SignInIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sentry-demo': typeof SentryDemoRoute
  '/api/inngest': typeof ApiInngestRoute
  '/sign-in/': typeof SignInIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sentry-demo' | '/api/inngest' | '/sign-in/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sentry-demo' | '/api/inngest' | '/sign-in'
  id: '__root__' | '/' | '/sentry-demo' | '/api/inngest' | '/sign-in/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SentryDemoRoute: typeof SentryDemoRoute
  ApiInngestRoute: typeof ApiInngestRoute
  SignInIndexRoute: typeof SignInIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sentry-demo': {
      id: '/sentry-demo'
      path: '/sentry-demo'
      fullPath: '/sentry-demo'
      preLoaderRoute: typeof SentryDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/': {
      id: '/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof SignInIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inngest': {
      id: '/api/inngest'
      path: '/api/inngest'
      fullPath: '/api/inngest'
      preLoaderRoute: typeof ApiInngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SentryDemoRoute: SentryDemoRoute,
  ApiInngestRoute: ApiInngestRoute,
  SignInIndexRoute: SignInIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
